/**
 * Market Types and Schemas
 * 
 * Type definitions and zod schemas for Polymarket weather markets.
 * Includes validation for Gamma API responses.
 */

import { z } from 'zod';
import type { ICAOCode } from '../config';
import type { PrecisionTemperature } from '../types/temperature';
import type { Timestamp } from '../types/timestamp';

/**
 * Market data structure
 * 
 * Represents a Polymarket weather prediction market with all
 * necessary information for trading decisions.
 */
export type Market = {
  readonly conditionId: string;
  readonly yesTokenId: string;
  readonly noTokenId: string;
  readonly icaoCode: ICAOCode;
  readonly threshold: PrecisionTemperature;      // Backward compatibility - single threshold
  readonly minThreshold: PrecisionTemperature;   // Range lower bound (can be -Infinity)
  readonly maxThreshold: PrecisionTemperature;   // Range upper bound (can be Infinity)
  readonly observationEnd: Timestamp;
  readonly ancillaryData: string;
  readonly description: string;
  readonly active: boolean;
};

/**
 * Zod schema for Gamma API market response
 * 
 * Validates the structure of market data returned from
 * Polymarket Gamma API.
 * 
 * NOTE: Gamma API uses camelCase for field names, not snake_case
 * NOTE: New API (/events/pagination) uses clobTokenIds instead of tokens array
 */
export const GammaMarketResponseSchema = z.object({
  conditionId: z.string(),
  question: z.string(),
  description: z.string().optional(),
  endDateIso: z.string().optional(),
  endDate: z.string().optional(),
  gameStartTime: z.string().optional(),
  questionId: z.string().optional(),
  marketSlug: z.string().optional(),
  minIncentiveSize: z.number().optional(),
  maxIncentiveSpread: z.number().optional(),
  active: z.boolean(),
  closed: z.boolean(),
  archived: z.boolean().optional(),
  acceptingOrders: z.boolean().optional(),
  // Old API format: tokens array
  tokens: z.array(z.object({
    tokenId: z.string(),
    outcome: z.string(),
    price: z.string().optional(),
    winner: z.boolean().optional(),
  })).optional().default([]),
  // New API format: clobTokenIds string (JSON array)
  clobTokenIds: z.string().optional(),
  // outcomes string (JSON array like '["Yes", "No"]')
  outcomes: z.string().optional(),
  rewards: z.object({
    minSize: z.string().optional(),
    maxSpread: z.string().optional(),
    eventStartDate: z.string().optional(),
    eventEndDate: z.string().optional(),
  }).optional(),
  // Ancillary data contains settlement rules and observation end time
  // This field may be in different locations depending on API version
  ancillaryData: z.string().optional(),
  umadata: z.string().optional(),
});

export type GammaMarketResponse = z.infer<typeof GammaMarketResponseSchema>;

/**
 * Zod schema for array of markets from Gamma API
 */
export const GammaMarketsArraySchema = z.array(GammaMarketResponseSchema);

/**
 * Order book data structure
 */
export type OrderBook = {
  readonly bids: Order[];
  readonly asks: Order[];
};

/**
 * Individual order in the order book
 */
export type Order = {
  readonly price: Price;
  readonly size: Size;
};

/**
 * Order side (buy or sell)
 */
export type Side = 'BUY' | 'SELL';

/**
 * Price type (0.0 to 1.0 representing probability)
 */
export type Price = number;

/**
 * Size type (USDC amount)
 */
export type Size = number;

/**
 * Order ID returned from CLOB API
 */
export type OrderID = string;

/**
 * Trading signal generated by the bot
 */
export type TradingSignal = {
  readonly market: Market;
  readonly currentTemp: PrecisionTemperature;
  readonly calculatedProbability: number;
  readonly marketPrice: Price;
  readonly ev: number;
  readonly timestamp: Timestamp;
  readonly action: 'BUY' | 'SELL' | 'HOLD';
  readonly recommendedPrice: Price;
  readonly recommendedSize: Size;
};

/**
 * Validate that a market response has required fields
 */
export function validateMarketResponse(data: unknown): GammaMarketResponse {
  return GammaMarketResponseSchema.parse(data);
}

/**
 * Validate array of market responses
 */
export function validateMarketsArray(data: unknown): GammaMarketResponse[] {
  return GammaMarketsArraySchema.parse(data);
}
