/**
 * Market Types and Schemas
 * 
 * Type definitions and zod schemas for Polymarket weather markets.
 * Includes validation for Gamma API responses.
 */

import { z } from 'zod';
import type { ICAOCode } from '../config';
import type { PrecisionTemperature } from '../types/temperature';
import type { Timestamp } from '../types/timestamp';

/**
 * Market data structure
 * 
 * Represents a Polymarket weather prediction market with all
 * necessary information for trading decisions.
 */
export type Market = {
  readonly conditionId: string;
  readonly yesTokenId: string;
  readonly noTokenId: string;
  readonly icaoCode: ICAOCode;
  readonly threshold: PrecisionTemperature;
  readonly observationEnd: Timestamp;
  readonly ancillaryData: string;
  readonly description: string;
  readonly active: boolean;
};

/**
 * Zod schema for Gamma API market response
 * 
 * Validates the structure of market data returned from
 * Polymarket Gamma API.
 */
export const GammaMarketResponseSchema = z.object({
  condition_id: z.string(),
  question: z.string(),
  description: z.string().optional(),
  end_date_iso: z.string(),
  game_start_time: z.string().optional(),
  question_id: z.string().optional(),
  market_slug: z.string().optional(),
  min_incentive_size: z.number().optional(),
  max_incentive_spread: z.number().optional(),
  active: z.boolean(),
  closed: z.boolean(),
  archived: z.boolean().optional(),
  accepting_orders: z.boolean().optional(),
  tokens: z.array(z.object({
    token_id: z.string(),
    outcome: z.string(),
    price: z.string().optional(),
    winner: z.boolean().optional(),
  })),
  rewards: z.object({
    min_size: z.string().optional(),
    max_spread: z.string().optional(),
    event_start_date: z.string().optional(),
    event_end_date: z.string().optional(),
  }).optional(),
  // Ancillary data contains settlement rules and observation end time
  // This field may be in different locations depending on API version
  ancillary_data: z.string().optional(),
  umadata: z.string().optional(),
});

export type GammaMarketResponse = z.infer<typeof GammaMarketResponseSchema>;

/**
 * Zod schema for array of markets from Gamma API
 */
export const GammaMarketsArraySchema = z.array(GammaMarketResponseSchema);

/**
 * Order book data structure
 */
export type OrderBook = {
  readonly bids: Order[];
  readonly asks: Order[];
};

/**
 * Individual order in the order book
 */
export type Order = {
  readonly price: Price;
  readonly size: Size;
};

/**
 * Order side (buy or sell)
 */
export type Side = 'BUY' | 'SELL';

/**
 * Price type (0.0 to 1.0 representing probability)
 */
export type Price = number;

/**
 * Size type (USDC amount)
 */
export type Size = number;

/**
 * Order ID returned from CLOB API
 */
export type OrderID = string;

/**
 * Trading signal generated by the bot
 */
export type TradingSignal = {
  readonly market: Market;
  readonly currentTemp: PrecisionTemperature;
  readonly calculatedProbability: number;
  readonly marketPrice: Price;
  readonly ev: number;
  readonly timestamp: Timestamp;
  readonly action: 'BUY' | 'SELL' | 'HOLD';
  readonly recommendedPrice: Price;
  readonly recommendedSize: Size;
};

/**
 * Validate that a market response has required fields
 */
export function validateMarketResponse(data: unknown): GammaMarketResponse {
  return GammaMarketResponseSchema.parse(data);
}

/**
 * Validate array of market responses
 */
export function validateMarketsArray(data: unknown): GammaMarketResponse[] {
  return GammaMarketsArraySchema.parse(data);
}
